services:
  estoreapi:
    image: ${DOCKER_REGISTRY-}estoreapi
    build:
      context: .
      dockerfile: src/Services/EStore.Api/Dockerfile
  distributedcache:
    image: redis
volumes:
  postgres_estoreapi:
  pgadmin_data:
