services:
  estoredb:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EStoreDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_estoreapi:/var/lib/postgresql/data/ 

  estoreapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=estoredb;Port=5432;Database=EStoreDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
    ports:
      - "8000:8080"
      - "8080:8081"
    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
      - $HOME/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
