services:
  estoredb:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EStoreDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_estoreapi:/var/lib/postgresql/data/ 

  estoreapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=estoredb;Port=5432;Database=EStoreDb;User Id=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "8000:8080"
      - "8080:8081"
    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
      - $HOME/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=nguyenvantien0620@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1
    ports:
      - "5050:80"
    depends_on:
      - estoredb
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always


  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
